# Generated by Django 5.1.1 on 2026-03-10 16:00

import business_forms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("instagram", "Instagram"), ("telegram", "Telegram")], max_length=20, verbose_name="Вы увидели эту анкету у меня в:")),
                ("mri_experience", models.CharField(choices=[("0-1_year", "0-1 год"), ("2-5_years", "2-5 лет"), ("resident_student", "я ординатор/студент"), ("other", "Другое")], max_length=30, verbose_name="Ваш опыт в МРТ")),
                ("mri_experience_other", models.CharField(blank=True, max_length=255, verbose_name="Ваш опыт в МРТ: другое")),
                ("specialization", models.CharField(choices=[("radiologist", "рентгенолог"), ("resident_student", "я ординатор/студент")], max_length=30, verbose_name="Ваша специальность")),
                ("mri_description_experience", models.TextField(verbose_name="У вас есть опыт описания МРТ")),
                ("city", models.CharField(max_length=120, verbose_name="Город проживания в настоящий момент (для понимания часового пояса)")),
                ("income_rub", models.CharField(max_length=120, verbose_name="Вас средний доход в месяц, в рублях")),
                ("difficult_sections", models.TextField(verbose_name="Какие разделы в МРТ у вас вызывают наибольшие трудности")),
                ("can_plan_mri", models.TextField(verbose_name="Вы умеете самостоятельно планировать МРТ исследования")),
                ("work_schedule", models.CharField(choices=[("until_14", "до 14.00"), ("14_to_20", "с 14.00 до 20.00"), ("night_shifts", "Ночные дежурства")], max_length=20, verbose_name="Ваш график работы")),
                ("convenient_time", models.TextField(verbose_name="Укажите удобное время для прохождения курса")),
                ("convenient_weekdays", models.TextField(verbose_name="Укажите удобные дни недели для прохождения курса")),
                ("full_name", models.CharField(max_length=200, verbose_name="Укажите ваше ФИО")),
                ("phone", models.CharField(max_length=30, verbose_name="Ваш номер телефона")),
                ("telegram", models.CharField(max_length=200, verbose_name="Ваш личный ник в телеграм для связи")),
                ("policy_agreement", models.BooleanField(default=False, verbose_name="Согласен с политикой обработки персональных данных")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Анкета предзаписи для рентгенологов",
                "verbose_name_plural": "Анкеты предзаписи для рентгенологов",
            },
        ),
        migrations.CreateModel(
            name="BusinessForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("photo", models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_photo_path)),
                ("spasibo_photo", models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_spasibo_path)),
                ("content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype")),
            ],
            options={
                "verbose_name": "Конфигурации форм",
                "verbose_name_plural": "Конфигурации форм",
            },
        ),
    ]
